slides:
    name: Slides
    singular_name: Slide
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        imagem:
            label: Imagem do Slide
            type: image
        url:
            label: Link de redirecionamento
            type: text
        destino:
            label: Destino do Link
            type: select
            values: { '_blank':"Nova Página", '_self':"Mesma Página" }
    recordsperpage: 10
    show_on_dashboard: false
    default_status: publish
    searchable: false

edicoes:
    name: Edições
    singular_name: Edição
    fields:
        titulo:
            label: Título da Edição
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        subtitulo:
            label: Subtítulo (geralmente hashtags)
            type: text
        corpo:
            label: Corpo de texto da edição
            type: html
            height: 300px
        imagem:
            type: image
    record_template: edicao.twig
    listing_template: edicoes.twig
    recordsperpage: 10
    show_on_dashboard: true
    default_status: publish
    searchable: true

artigos:
    name: Artigos
    singular_name: Artigo
    fields:
        titulo:
            label: Título do Artigo
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        corpo:
            label: Conteúdo do Artigo
            type: html
            height: 300px
        imagem:
            label: Imagem de Destaque
            type: image
        remover:
            label: Remover destaque do post?
            type: checkbox
    relations:
        edicoes:
            multiple: false
            label: "Escolha a Edição do TED para este artigo"
            order: -id
    recordsperpage: 10
    show_on_dashboard: true
    default_status: publish
    searchable: true

paginas:
    name: Páginas
    singular_name: Página
    fields:
        titulo:
            label: Título
            type: text
            class: large
            group: Título
        slug:
            type: slug
            uses: titulo
        corpo-coluna-1:
            label: Conteúdo exibido na coluna da esquerda
            type: html
            height: 300px
            group: Coluna 1
        class-coluna-1:
            label: "Classes da coluna (Ex: col-xs-4)"
            type: text
            group: Coluna 1
        corpo-coluna-2:
            label: Conteúdo exibido na coluna da direita
            type: html
            height: 300px
            group: Coluna 2
        class-coluna-2:
            label: "Classes da coluna (Ex: col-xs-4)"
            type: text
            group: Coluna 2
    record_template: pagina.twig
    recordsperpage: 10
    show_on_dashboard: true
    default_status: publish
    searchable: false

config:
    name: Config
    singular_name: Config
    fields:
        titulo:
            label: Título da configuração
            type: text
            class: large
            group: Título e logo
        slug:
            type: slug
            uses: titulo
        logo:
            label: Logo principal do site
            type: image
        corpo-coluna-1:
            label: Conteúdo da primeira coluna
            type: html
            height: 300px;
            group: Rodapé
        corpo-coluna-2:
            label: Conteúdo da segunda coluna
            type: html
            height: 300px;
            group: Rodapé
        corpo-coluna-3:
            label: Conteúdo da terceira coluna
            type: html
            height: 300px;
            group: Rodapé
    recordsperpage: 1
    show_on_dashboard: false
    searchable: false
    viewless: true