main:
  - label: sobre
    title: Sobre a Mostra TED no Território do Bem.
    path: pagina/sobre
    class: first
  - label: onde?
    path: pagina/onde
  - label: edições
    path: edicoes
  - label: nós
    path: pagina/nos
  - label: contato
    path: pagina/contato
    class: last
